version: '3.8'

services:
  cli-app:
    build: .
    image: cli-app:latest
    container_name: cli-app-service
    stdin_open: true
    tty: true
    restart: unless-stopped
    env_file:
      - .env